version: '3.7'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: tanafaso
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data_container:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
  tanafaso-server:
    depends_on:
      mongo:
        condition: service_healthy
    build:
      dockerfile: Dockerfile-Run
    ports:
      - 8080:8080
    volumes:
      - maven-cache:/root/.m2
    environment:
      DATABASE_URI: mongodb://mongo:27017/tanafaso
      SERVER_PORT: 8080
      JWT_SECRET: example-secret
      LOGS_PATH: ./logs
      MAIL_HOST: smtp.gmail.com
      MAIL_USERNAME: example@example.com
      MAIL_PASSWORD: example-mail-password
      MAIL_PORT: 587
      APPLE_TEAM_ID: example-apple-team-id
      APPLE_SIGN_IN_KEY_ID: example-apple-sign-in-key

volumes:
  mongodb_data_container:
  maven-cache: