name: API - Build, Test & Package

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
  pull_request:
    branches:
      - master
    paths:
      - 'api/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Mongo DB
        run: docker compose -f docker-compose-test.yml up -d mongo
      
      - name: Check for resource leaks and code issues
        run: |
          docker compose -f docker-compose-test.yml run --rm tanafaso-test mvn compile -Dmaven.compiler.showWarnings=true 2>&1 | tee compile.log
          if grep -i "resource leak" compile.log; then
            echo "❌ Resource leaks detected!"
            exit 1
          fi
        
      - name: Test & Package Tanafaso
        run: docker compose -f docker-compose-test.yml up tanafaso-test
